# Generated by Django 3.2 on 2021-05-08 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('category', models.CharField(choices=[('简历指导', '简历指导'), ('就业协议', '就业协议'), ('户口档案', '户口档案'), ('职业规划', '职业规划')], max_length=20, verbose_name='分类')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '就业指导',
                'verbose_name_plural': '就业指导',
            },
        ),
    ]
