# Generated by Django 3.2 on 2021-05-09 21:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('address', models.CharField(max_length=20, verbose_name='地点')),
                ('leave_message', models.CharField(max_length=100, verbose_name='留言')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interview_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interview_sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '面试邀请记录',
                'verbose_name_plural': '面试邀请记录',
            },
        ),
    ]
