# Generated by Django 3.2 on 2021-05-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_interviewrecord_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='times',
            field=models.IntegerField(default=1, verbose_name='面试第几轮'),
        ),
    ]
