# Generated by Django 3.2 on 2021-05-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_interviewrecord_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='status',
            field=models.CharField(choices=[('待面试', '待面试'), ('已通过', '已通过'), ('未通过', '未通过')], default='待面试', max_length=10, verbose_name='是否通过'),
        ),
    ]
