# Generated by Django 3.2 on 2021-05-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_remove_position_resume_template'),
        ('interview', '0004_interviewrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='position.position'),
        ),
    ]
