# Generated by Django 3.2 on 2021-05-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interviewrecord_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='end_time',
            field=models.TimeField(null=True),
        ),
    ]
