# Generated by Django 3.2 on 2021-05-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_alter_interviewrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewrecord',
            name='status',
            field=models.CharField(choices=[('待面试', '待面试'), ('邀请中', '邀请中'), ('已通过', '已通过'), ('未通过', '未通过'), ('已接受面试', '已接受面试'), ('已拒绝面试', '已拒绝面试'), ('已发放offer', '已发放offer'), ('已接受offer', '已接受offer'), ('已拒接offer', '已拒接offer')], default='待面试', max_length=10, verbose_name='是否通过'),
        ),
    ]
