# Generated by Django 3.2 on 2021-06-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resumeposition_status'),
        ('interview', '0009_alter_interviewrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrecord',
            name='resume_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resumeposition'),
        ),
        migrations.AlterField(
            model_name='interviewrecord',
            name='status',
            field=models.CharField(choices=[('待面试', '待面试'), ('邀请中', '邀请中'), ('已通过', '已通过'), ('未通过', '未通过'), ('已接受面试', '已接受面试'), ('已拒绝面试', '已拒绝面试'), ('已发放offer', '已发放offer'), ('已接受offer', '已接受offer'), ('已拒接offer', '已拒接offer')], default='邀请中', max_length=10, verbose_name='是否通过'),
        ),
    ]
