# Generated by Django 3.2 on 2021-05-08 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('head_img', models.ImageField(upload_to='enterprise/head_img/', verbose_name='头像')),
                ('field', models.CharField(max_length=30, verbose_name='行业领域')),
                ('worker_num', models.IntegerField(verbose_name='员工数')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('desc', models.TextField(verbose_name='简介')),
                ('finance', models.CharField(choices=[('未融资', '未融资'), ('天使轮', '天使轮'), ('A轮', 'A轮'), ('B轮', 'B轮'), ('C轮', 'C轮'), ('D轮', 'D轮'), ('上市企业', '上市企业')], default='未融资', max_length=10, verbose_name='融资阶段')),
                ('contact', models.CharField(max_length=11, verbose_name='联系方式')),
                ('slogan', models.CharField(blank=True, max_length=50, null=True, verbose_name='口号')),
            ],
            options={
                'verbose_name': '企业',
                'verbose_name_plural': '企业',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('end_time', models.DateTimeField()),
                ('school', models.CharField(max_length=20, verbose_name='举办学校')),
                ('address', models.CharField(max_length=20, verbose_name='具体地点')),
                ('desc', models.TextField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.enterprise')),
            ],
            options={
                'verbose_name': '宣讲会',
                'verbose_name_plural': '宣讲会',
            },
        ),
    ]
