# Generated by Django 3.2 on 2021-05-08 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0002_enterprise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
