# Generated by Django 3.2 on 2021-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_alter_lecture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='welfare',
            field=models.TextField(null=True, verbose_name='薪资福利'),
        ),
    ]
