# Generated by Django 3.2 on 2021-05-13 17:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprise', '0005_lecture_welfare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='date',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='school',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_time',
        ),
        migrations.CreateModel(
            name='Fair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('school', models.CharField(max_length=20, verbose_name='举办学校')),
                ('address', models.CharField(max_length=20, verbose_name='具体地点')),
                ('desc', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '招聘会',
                'verbose_name_plural': '招聘会',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='fair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.fair'),
        ),
    ]
