# Generated by Django 3.2 on 2021-05-13 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0006_auto_20210513_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='address',
            field=models.CharField(max_length=20, null=True, verbose_name='具体地点'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='date',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='school',
            field=models.CharField(max_length=20, null=True, verbose_name='举办学校'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
