# Generated by Django 3.2 on 2021-05-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0007_auto_20210513_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='fair',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.enterprise'),
        ),
    ]
