# Generated by Django 3.2 on 2021-05-22 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0008_fair_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fair',
            name='enterprise',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='fair',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='welfare',
        ),
        migrations.CreateModel(
            name='EnterpriseFair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.enterprise')),
                ('fair', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.fair')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
