# Generated by Django 3.2 on 2021-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_auto_20210522_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='官网链接'),
        ),
    ]
