# Generated by Django 3.2 on 2021-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0011_auto_20210526_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='license',
            field=models.CharField(max_length=200, null=True, verbose_name='企业证明'),
        ),
    ]
