# Generated by Django 3.2 on 2021-05-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0012_enterprise_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='license',
            field=models.ImageField(null=True, upload_to='enterprise/license', verbose_name='企业证明'),
        ),
    ]
