# Generated by Django 3.2 on 2021-05-09 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0002_remove_position_resume_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('file', models.FileField(upload_to='resume/', verbose_name='简历附件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历附件',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('edu', models.CharField(choices=[('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=10, verbose_name='学历')),
                ('university', models.CharField(max_length=20, verbose_name='毕业学校')),
                ('profession', models.CharField(max_length=20, verbose_name='专业')),
                ('want', models.CharField(max_length=20, verbose_name='求职意向')),
                ('desc', models.TextField(verbose_name='个人简介')),
                ('contact', models.CharField(max_length=11, verbose_name='联系方式')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
            },
        ),
        migrations.CreateModel(
            name='ResumePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('status', models.CharField(choices=[('待审核', '待审核'), ('已通过', '已通过'), ('未通过', '未通过')], default='待审核', max_length=10)),
                ('file_resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resume.fileresume')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='position.position', verbose_name='职位')),
                ('resume', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resume.resume')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '职位申请记录',
                'verbose_name_plural': '职位申请记录',
            },
        ),
    ]
