# Generated by Django 3.2 on 2021-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210509_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeposition',
            name='category',
            field=models.CharField(choices=[('在线简历', '在线简历'), ('简历附件', '简历附件')], max_length=10, null=True, verbose_name='简历类型'),
        ),
    ]
