# Generated by Django 3.2 on 2021-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resumeposition_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeposition',
            name='status',
            field=models.CharField(choices=[('待审核', '待审核'), ('审核通过', '审核通过'), ('未通过', '未通过'), ('邀请中', '邀请中'), ('面试中', '面试中'), ('面试通过', '面试通过')], default='待审核', max_length=10),
        ),
    ]
