# Generated by Django 3.2 on 2021-05-08 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('category', models.CharField(max_length=30, verbose_name='分类')),
                ('min_salary', models.IntegerField(verbose_name='最少薪资')),
                ('max_salary', models.IntegerField(verbose_name='最高薪资')),
                ('edu_require', models.CharField(choices=[('大专', '大专'), ('本科', '本科'), ('硕士', '硕士'), ('博士', '博士')], max_length=10, verbose_name='学位需求')),
                ('skill_require', models.TextField(verbose_name='技能需求')),
                ('min_work_year', models.IntegerField(default=0, verbose_name='最低工作年限')),
                ('desc', models.TextField(verbose_name='简介')),
                ('num', models.IntegerField(verbose_name='招聘人数')),
                ('resume_template', models.FileField(blank=True, null=True, upload_to='position/resume_template', verbose_name='简历模板')),
                ('interview', models.IntegerField(default=1, verbose_name='面试轮次')),
                ('professions', models.TextField(null=True, verbose_name='招聘专业')),
                ('work_address', models.TextField(null=True, verbose_name='工作地点')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise', verbose_name='企业')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
            },
        ),
    ]
