# Generated by Django 3.2 on 2021-05-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_position_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='is_internship',
            field=models.BooleanField(default=False, verbose_name='是否实习'),
        ),
    ]
