# Generated by Django 3.2 on 2021-05-22 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0009_auto_20210522_1616'),
        ('position', '0005_position_is_internship'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.lecture')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='position.position')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
