# Generated by Django 3.2 on 2021-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_auto_20210524_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='tags',
            field=models.JSONField(default=[], null=True),
        ),
    ]
