# Generated by Django 3.2 on 2021-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0008_alter_position_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='tags',
            field=models.JSONField(default=['五险一金'], null=True),
        ),
    ]
