# Generated by Django 3.2 on 2021-05-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0009_alter_position_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='work_kind',
            field=models.CharField(max_length=10, null=True, verbose_name='工作性质'),
        ),
    ]
