# Generated by Django 3.2 on 2021-05-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0010_position_work_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
