kubectl apply -f development/cloud/auth/secret.yaml
kubectl apply -f development/cloud/endpoints.yaml
kubectl apply -f development/cloud/auth/development.yaml
kubectl apply -f development/cloud/gateway/development.yaml
kubectl apply -f development/cloud/gustav/development.yaml
kubectl apply -f development/cloud/dow/development.yaml
kubectl apply -f development/cloud/mond/development.yaml
kubectl apply -f development/cloud/engineering/development.yaml
kubectl apply -f development/cloud/fireloss/development.yaml
kubectl apply -f development/cloud/accsim/development.yaml