# Generated by Django 3.2 on 2021-05-21 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
    ]
