export namespace mondUrl {
    export const MaterialCoefficientSaveUnknownMaterial = "/mond/MaterialCoefficientSaveUnknownMaterial"
    export const MaterialCoefficientGetKnownCoefficient = "/mond/MaterialCoefficientGetKnownCoefficient"
    export const MaterialCoefficientGetKnownNames = "/mond/MaterialCoefficientGetKnownNames"
    export const MaterialCoefficient = "/mond/MaterialCoefficient"
    export const SpecialMaterialHazard = "/mond/SpecialMaterialHazard"
    export const GeneralProcessHazard = "/mond/GeneralProcessHazard"
    export const SpecialProcessHazard = "/mond/SpecialProcessHazard"
    export const ArrangementHazardCoefficient = "/mond/ArrangementHazardCoefficient"
    export const NumHazardCoefficient = "/mond/NumHazardCoefficient"
    export const PoisonHazardCoefficient = "/mond/PoisonHazardCoefficient"
    export const PoisonHazardCoefficientGetTLVTypeExposure = "/mond/PoisonHazardCoefficientGetTLVTypeExposure"
    export const ContainerSystemCoefficient = "/mond/ContainerSystemCoefficient"
    export const ProcessManagementCoefficient = "/mond/ProcessManagementCoefficient"
    export const MaterialIsolationCoefficient = "/mond/MaterialIsolationCoefficient"
    export const SafetyAttitudeCoefficient = "/mond/SafetyAttitudeCoefficient"
    export const FirePreventionCoefficient = "/mond/FirePreventionCoefficient"
    export const FireFightingActivityCoefficient = "/mond/FireFightingActivityCoefficient"
    export const InitialCommentIndexFinialCompensationCoefficient = "/mond/InitialCommentIndexFinialCompensationCoefficient"
    export const MaterialsGet = "/mond/MaterialsGet"
    export const MaterialEdit = "/mond/MaterialEdit"
    export const MaterialDelete = "/mond/MaterialDelete"

}