# Generated by Django 3.2 on 2021-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_opt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='obj_type',
            field=models.CharField(choices=[('职位', '职位'), ('宣讲会', '宣讲会')], max_length=20, null=True, verbose_name='历史对象类型'),
        ),
    ]
