# Generated by Django 3.2 on 2021-05-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_opt', '0002_history_obj_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='obj_type',
        ),
    ]
