# Generated by Django 3.2 on 2021-05-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_opt', '0003_remove_history_obj_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
