# Generated by Django 3.2 on 2021-05-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_opt', '0005_consult'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='status',
            field=models.CharField(choices=[('未读', '未读'), ('已读', '已读'), ('已回复', '已回复')], default='未读', max_length=10),
        ),
    ]
